### ISSUE TITLE
Creating an AWS instance not working with jruby 1.7.0

### ISSUE THREAD

**Issue by scottpayne** [fog/fog#1286]
Hopefully this is just something with my environment. I've been trying to use rubber to set up an AWS instance for a jruby rails project and it is just not playing nicely. I've tracked it down to fog and can reproduce the error without rubber being involved at all. 

It works fine with ruby 1.9.3.

I've tried various jruby-openssl 0.7.4, 0.7.7 and the version shipped with jruby.

I've tried jruby 1.7.0 and the current head.

I've tried running jruby with `--1.8` and `--1.9`.

The error goes:

```
NoMethodError: undefined method `each' for nil:NilClass
  merge_attributes at <home>/.rvm/gems/jruby-1.7.0@project/gems/fog-1.7.0/lib/fog/core/attributes.rb:143
              save at <home>/.rvm/gems/jruby-1.7.0@project/gems/fog-1.7.0/lib/fog/aws/models/compute/server.rb:168
            create at <home>/.rvm/gems/jruby-1.7.0@project/gems/fog-1.7.0/lib/fog/core/collection.rb:50
   create_instance at <home>/.rvm/gems/jruby-1.7.0@project/gems/rubber-2.1.2/lib/rubber/cloud/fog.rb:27
              send at org/jruby/RubyKernel.java:2072
    method_missing at <home>/.rvm/gems/jruby-1.7.0@project/gems/rubber-2.1.2/lib/rubber/thread_safe_proxy.rb:13
   create_instance at <home>/.rvm/gems/jruby-1.7.0@project/gems/rubber-2.1.2/lib/rubber/recipes/rubber/instances.rb:297
  create_instances at <home>/.rvm/gems/jruby-1.7.0@project/gems/rubber-2.1.2/lib/rubber/recipes/rubber/instances.rb:217
              call at org/jruby/RubyProc.java:261
              call at org/jruby/RubyProc.java:213
```

Taking rubber out of the picture, I've managed to reproduce the error with this little script:

``` ruby
#!/usr/bin/env ruby
require 'fog'

compute = Fog::Compute[:aws]
server = compute.servers.new(:image_id => "ami-fefcbcac", :flavor_id => "t1.micro", :key_name => "mydevkey")
begin
  server.save
rescue Exception => e
  puts e.backtrace
  puts "Nope, still broked. Cleaning up"
  compute.servers.select { |s| s.state == 'running' }.each { |s| s.destroy }
  puts "Done!"
end
```

It needs to do the cleanup because it creates the instance and sets it running, then dies with the above error.

The minimal gem bundle to get the above script to go is just a `gem "fog"` in the Gemfile:

```
Gems included by the bundle:
  * builder (3.1.4)
  * bundler (1.2.2)
  * excon (0.16.10)
  * fog (1.7.0)
  * formatador (0.2.4)
  * mime-types (1.19)
  * multi_json (1.3.7)
  * net-scp (1.0.4)
  * net-ssh (2.6.1)
  * nokogiri (1.5.5)
  * ruby-hmac (0.4.0)
```

Feel free to call me an idiot if it's something simple and I just didn't RTFM.
