### ISSUE TITLE
Openstack 1.36.0 now fails to list tenants

### ISSUE THREAD

**Issue by drich10** [fog/fog#3770]
Works in 1.35.0, now fails.  
Stacktrace:
```
/Users/pivotal/.gem/ruby/2.2.3/gems/fog-1.36.0/lib/fog/openstack/requests/compute/list_tenants.rb:6:in `list_tenants': undefined method `request' for nil:NilClass (NoMethodError)
	from /Users/pivotal/.gem/ruby/2.2.3/gems/fog-1.36.0/lib/fog/openstack/models/compute/tenants.rb:11:in `all'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/fog-core-1.34.0/lib/fog/core/collection.rb:113:in `lazy_load'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/fog-core-1.34.0/lib/fog/core/collection.rb:17:in `map'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/fog-core-1.34.0/lib/fog/formatador.rb:85:in `inspect_object'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/fog-core-1.34.0/lib/fog/formatador.rb:72:in `block in nested_objects_string'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/formatador-0.2.5/lib/formatador.rb:92:in `indent'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/fog-core-1.34.0/lib/fog/formatador.rb:41:in `indent'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/fog-core-1.34.0/lib/fog/formatador.rb:72:in `nested_objects_string'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/fog-core-1.34.0/lib/fog/formatador.rb:54:in `object_string'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/fog-core-1.34.0/lib/fog/formatador.rb:14:in `block in format'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/formatador-0.2.5/lib/formatador.rb:92:in `indent'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/fog-core-1.34.0/lib/fog/formatador.rb:41:in `indent'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/fog-core-1.34.0/lib/fog/formatador.rb:14:in `format'
	from /Users/pivotal/.gem/ruby/2.2.3/gems/fog-core-1.34.0/lib/fog/core/collection.rb:73:in `inspect'
	from /Users/pivotal/Library/Preferences/RubyMine80/scratches/scratch_3:15:in `p'
	from /Users/pivotal/Library/Preferences/RubyMine80/scratches/scratch_3:15:in `<top (required)>'
```

Here's the code that we use to verify the bug:
```ruby
gem 'fog', '1.36.0'
require 'fog'

c = Fog::Compute.new({
  provider: 'openstack',
  openstack_auth_url: 'http://10.85.40.2:5000/v2.0/tokens',
  openstack_identity_endpoint: 'http://10.85.40.2:5000/v2.0',
  openstack_username: 'admin',
  openstack_api_key: 'admin',
  openstack_region: 'RegionOne',
  connection_options: {}
})

p c.tenants
```

**Comment by seanhandley** [comment]
Can you show the same code working correctly in 1.35.0 @drich10  ?

I'm having no trouble viewing tenants in my code.

**Comment by seanhandley** [comment]
Also, why are you using `Fog::Compute` and not `Fog::Identity` ?

**Comment by drich10** [comment]
The code is the exact same for version 1.35, all we do is replace the version in the first line. We are currently using Compute because we are making these calls from outside our Openstack environment and the Identity class attempts to use the internal IPs of the services.

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-openstack#55
