### ISSUE TITLE
undefined method `redisplay_progressbar' for Fog::Formatador:Class

### ISSUE THREAD

**Issue by davehatton** [fog/fog#3398]
After upgrading from 1.25 to 1.27 the following error 

undefined method `redisplay_progressbar' for Fog::Formatador:Class

is generated by fog-1.27.0/lib/fog/vcloud_director/models/compute/task.rb

The problem occurs when calling fog from the vcloud-tools gem when creating a new VM in a vcloud_director/Skyscape environment.

Downgrading to 1.25 resolves the issue.

**Comment by plribeiro3000** [comment]
Closed in favor of fog/fog-core#121

**Comment by plribeiro3000** [comment]
Please follow that one instead.
