### ISSUE TITLE
S3 Buckets with periods in them Fail

### ISSUE THREAD

**Issue by seigel** [fog/fog#3421]
I know amazon updated their restrictions at some point, but they don't disallow people (like myself) from making buckets with dots in them.  I can't fog with the latest version for some reason.

... .rvm/gems/ruby-2.1.4/gems/fog-aws-0.0.8/lib/fog/aws/storage.rb:606:in `rescue in _request': undefined method `captures' for nil:NilClass (NoMethodError)

**Comment by geemus** [comment]
I think it may just be a corner case where both the bucket has periods and the region specified doesn't match the bucket, but I could be wrong. Could you describe the context a bit more?

**Comment by seigel** [comment]
I will look into it more, and update

**Comment by seigel** [comment]
It seems like if I don't specify the region (as you suggest), then I have issues.
WIN:
 {provider: 'AWS', aws_access_key_id: <a key>, aws_secret_access_key: <another key>, region: 'us-west-1'}
FAIL: 
 {provider: 'AWS', aws_access_key_id: <a key>, aws_secret_access_key: <another key>}

Weird.  It all works fine with fog 1.3.1

**Comment by fcheung** [comment]
Is this a dupe of fog/fog-aws#33?

**Comment by geemus** [comment]
@fcheung quite possibly (and/or 33 didn't fix it for all cases)

**Comment by plribeiro3000** [comment]
@seigel It seems your error is related to fog/fog-aws#33. Please follow up there if a `bundle update fog-aws` does not solve your issue.

Thanks!
